### ISSUE TITLE
missing header file

### ISSUE THREAD

**Issue by yuanxuns** [thvasilo/cuda-sgd-sese-project#1]
Hello, I have trouble while running the program. The header file "sampling.cuh" in main.cu is missing. Could you please fix the issue? Thanks.

**Comment by thvasilo** [comment]
Hello @YuanxunShao, if I'm being honest I don't remember why that particular header file is being imported. Maybe you can try commenting it out and see if the code compiles, as of now I'm deprecating this repo to indicate I'm no longer supporting it though.
